var n = 5;
console.log(n == 5);
console.log(n === 5);
console.log(n != 5);
console.log(n <= 8);
console.log(n >= 8);
var n = 5;
console.log(n >= 5 && n < 10);
console.log(n > 5 && n < 10);
console.log(n >= 5 || n < 10);
console.log(n >= 5 || n > 10);
console.log(!(n < 10));
console.log(!(n > 10));
